---
language: ruby
rvm:
- "2.3.8"
- "2.4.9"
- "2.5.7"
- "2.6.5"
- ruby-head
- jruby-head
sudo: false
cache: bundler
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  fast_finish: true
